### ISSUE TITLE
Long Snippets?

### ISSUE THREAD

**Issue by ToluClassics** [ToluClassics/candle-tutorial#2]
Hi @LaurentMazare, I started putting [this together](https://github.com/ToluClassics/candle-tutorial/blob/main/README.md) as part of https://github.com/huggingface/candle/issues/1075. It's a good idea to include code snippets across both Pytorch and Candle in the document but I'm likely to end up with a really long write-up. I was able to convert Roberta and XLM-R models and I intend to do RWKV next.

I was wondering if you had any particular directions in mind on how to document the conversion.

**Comment by LaurentMazare** [comment]
That's nice, I think it's fine to have a long writeup - my guess is that you should really put the text that you wish existed when trying to port your first model. One thing that would be nice to have too besides the model porting is how to write a small binary to run the model on some sample task though maybe that's orthogonal.
